# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('uid', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('identity', models.CharField(max_length=1)),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('sex', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('birthday', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('position', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=60, null=True)),
            ],
        ),
    ]
