# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eltip_user', '0002_auto_20160625_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='credit',
            field=models.CharField(max_length=30),
        ),
    ]
