# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eltip_user', '0003_auto_20160625_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
